### ISSUE TITLE
getBucketVersioningStatus will return null when the provided info is missing (e.g. on IBM cloud storage) 

### ISSUE THREAD

**Issue by alexander-riss** [iterate-ch/jets3t#10]
this causes null pointer exceptions further up the chain (and e.g. prevents cyberduck from connecting to ibm object storage solutions). Maybe adding a default in https://github.com/iterate-ch/jets3t/blob/f9978abceb740f32de8c014d86efff6e8b6c728e/src/org/jets3t/service/impl/rest/httpclient/RestS3Service.java#L492 if the parser returns null would be a more robust solution?

**Comment by alexander-riss** [comment]
@dkocher do you think this would be possible and or something you would accept to merge?

**Comment by dkocher** [comment]
Sorry for the late follow-up here. If this is still an issue please file a bug report in Cyberduck [^1] as we have made several connection profiles available for IBM Cloud Object Storage which are expected to work.

[^1]: https://github.com/iterate-ch/cyberduck/issues/new/choose
